Create basic library structure
dylan-lang/zlib pull request #8
Opened 2024-05-29 08:23 UTC by fraya

Adapt library to include basic structure:

- Standard library structure of modules and directories.
- Package description.
- Basic tests.
- Basic documentation.

2024-05-29 20:01 UTC, cgay requested changes
LGTM

2024-05-29 20:01 UTC, cgay commented on documentation/source/reference.rst
> +This functions are implemented on top of the basic zlib
These functions...

2024-05-29 20:01 UTC, cgay commented on tests/zlib-test-suite.lid
> +       zlib-test-suite
Either omit all file extensions (.dylan) or use them everywhere.

2024-05-30 06:49 UTC, fraya commented on documentation/source/reference.rst
> +This functions are implemented on top of the basic zlib
Fixed.

2024-05-30 06:49 UTC, fraya commented on tests/zlib-test-suite.lid
> +       zlib-test-suite
Fixed.

2024-05-30 06:50 UTC, merged