Add compress and uncompress utility methods
dylan-lang/zlib pull request #9
Opened 2024-10-09 08:06 UTC by fraya

Add utility methods compress, uncompress and documentation.

2024-10-09 08:21 UTC, waywardmonkeys requested changes
This shouldn't be using strings / c-strings / etc in this way but rather something like what I did in the leveldb bindings: https://github.com/dylan-foundry/leveldb-dylan

Using `byte-storage-address` will work for a couple of types, I don't recall the full details at the moment.

But at any rate, the byte data shouldn't be stored into regular strings.

2024-10-09 08:22 UTC, waywardmonkeys commented
(If you need help with how to do that stuff, let me me know here or elsewhere and I'll find the time to help you figure it out.)

2024-10-10 05:46 UTC, fraya commented
Thank you for your support. I'll read leveldb-dylan and ask you for help later.

2024-10-29 00:54 UTC, cgay reviewed
Just a bunch of nit-picking on the documentation. Feel free to ignore it or fix it in a separate PR.

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +This module binds the functions of the zlib library.
Something like this is a little more explicit: "This module creates Dylan bindings that directly reflect the zlib C library."

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +Return codes for the compression/decompression
You should delete "the" here. Perhaps "Return codes for (de)compression functions"

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +   If a preset dictionary is needed.
A preset dictionary is needed.

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +   Returned if the operation was a success.
Optional: you could remove "Returned if" from all these constants since that part is implied. In this case: "The operation was a success."  It's up to you though; either way is perfectly clear.

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +   output buffer when ``$z-finish`` is used.
Remove both "if"s and be consistent with tense: was possible ... was used.

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +the input is simply copied a block a time).
Missing an "at".  "...a block at a time)."  Same problem below.

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +   Requests a default compromise between speed and compression
A compromise between ....

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +   earlier.
Instead of ``` ``$z-text`` ``` use ``` :const:`$z-text`_ ```

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +   version).
...the only _one_ supported ...

(It's weird, right? It's like saying "el único uno que..." or something like that, instead of "el único que".)

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +      :drm:`<integer>`
Dylan doesn't have "out" parameters so it's not possible for `destination-length` to contain the actual size on exit. Not sure what this should say instead. Delete the middle sentence?

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +      :const:`$z-default-compression`.
Remove "It's"

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +      z-compress-2 *string* *destination-length* *source* *source-length* *level* => (*return-code*)
`*string*` should be `*destination*`

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +      An instance of :class:`<C-string>`
In the code this is type `<c-buffer-offset>`.  Not sure what that is.

2024-10-29 00:54 UTC, cgay commented on documentation/source/zlib-binding.rst
> +   :func:`z-compress-2` call to allocate the destination buffer.
It _may_ be used ... to decide the size of the destination buffer.

2024-10-29 16:53 UTC, merged